---
  - name: Install ELK Playbook
    hosts: elk
    become: true
    tasks:

    - name: Install docker_io  (state=present is optional)
      apt:
        force_apt_get: yes
        update_cache: yes
        name: docker.io
        state: present

    - name: Install pip3  (state=present is optional)
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: set vm.max_map_count to 262144 in sysctl
      sysctl:
        name: vm.max_map_count
        value: "262144"
        state: present
        reload: yes

    - name: Install Docker Python module  (state=present is optional)
      pip:
        name: docker
        state: present

    - name: Download and launch a docker web container   (state=present is optional)
      docker_container:
        name: elk
        image: sebp/elk:761
        restart_policy: always
        state: started
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044

    - name: docker start exciting_napier  (state=present is optional)
      systemd:
        name: docker
        enabled: yes

  - name: installing and launching filebeat
    hosts: webservers
    become: yes
    tasks:

    - name: download filebeat deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

    - name: install filebeat deb
      command: sudo dpkg -i filebeat-7.6.1-amd64.deb

    - name: drop in filebeat.yml
      copy:
        src: /etc/ansible/files/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml

    - name: enable and configure system module
      command: sudo filebeat modules enable system

    - name: setup filebeat
      command: sudo filebeat setup

    - name: start filebeat service
      command: sudo service filebeat start

    - name: enable service filebeat on boot
      systemd:
        name: filebeat
        enabled: yes
        
  - name: Install metric beat
    hosts: webservers
    become: true
    tasks:
      # Use command module
    - name: Download metricbeat
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

      # Use command module
    - name: install metricbeat
      command: sudo dpkg -i metricbeat-7.6.1-amd64.deb


      # Use copy module
    - name: drop in metricbeat config
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

      # Use command module
    - name: enable and configure docker module for metric beat
      command: sudo metricbeat modules enable docker

      # Use command module
    - name: setup metric beat
      command: sudo metricbeat setup

      # Use command module
    - name: start metric beat
      command: sudo service metricbeat start

      # Use systemd module
    - name: enable service metricbeat on boot
      systemd:
        name: metricbeat
        enabled: yes