---
  - name: Install ELK Playbook
    hosts: elk
    become: true
    tasks:

    - name: Install docker_io  (state=present is optional)
      apt:
        force_apt_get: yes
        update_cache: yes
        name: docker.io
        state: present

    - name: Install pip3  (state=present is optional)
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: set vm.max_map_count to 262144 in sysctl
      sysctl:
        name: vm.max_map_count
        value: "262144"
        state: present
        reload: yes

    - name: Install Docker Python module  (state=present is optional)
      pip:
        name: docker
        state: present

    - name: Download and launch a docker web container   (state=present is optional)
      docker_container:
        name: elk
        image: sebp/elk:761
        restart_policy: always
        state: started
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044

    - name: docker start exciting_napier  (state=present is optional)
      systemd:
        name: docker
        enabled: yes